### ISSUE TITLE
patch creator fails with Gen2 FW1633

### ISSUE THREAD

**Issue by foucar** [JohnRev/rrlogd-patcher#1]
The patcher script doesn't work with the rrlogd binary from firmware 1633 for the RoborockS50.

Here is the output when running the script:
```
$ python3 patcher.py
Original 00010549:  FE, 33, 46, 4B, A8, 10, 22
Patched  00010549:  FE, 33, 46, 47, A8, 10, 22
Patch has failed
```
Here is some info about the vaccum:
```
$ mirobo --ip 192.168.123.105 --token XXXXXX info
roborock.vacuum.s5 v3.3.9_001633 ...
```
Please find the unpatched rrlogd attached below
[rrlogd.zip](https://github.com/JohnRev/rrlogd-patcher/files/2732891/rrlogd.zip)

**Comment by cryptomilk** [comment]
This only supports v001780 and newer.

**Comment by JohnRev** [comment]
Thanks for opening this issue, @foucar.
As @cryptomilk mentioned, this was primarily developed for v1780 and newer.

I have analyzed the attached rrlogd, and there's a small modification required for the patch to work.

In the python file, replace lines 11 and 12 with:
```python
patterns = [b"\xF2\x04\x03\xFF\xF7\x4B\xFF", b"\xFE\x33\x46\x4B\xA8\x10\x22"]
replaces = [b"\xF2\x04\x03\xE3\x20\x4B\xFF", b"\xFE\x33\x46\x47\xA8\x10\x22"]
```

The patch should then work.

**Comment by JohnRev** [comment]
Updated `patcher.py` with new paterns
