### ISSUE TITLE
Patch fails for 3.3.9_001856

### ISSUE THREAD

**Issue by peter--s** [JohnRev/rrlogd-patcher#5]
Hello JohnRev,

While 3.3.9_001818 seems to work without issues, 3.3.9_001856 does not seem to contain any of the patterns.
(The patched newer rrlogd you provide in https://github.com/JohnRev/rrlogd-patcher/issues/4#issuecomment-615754995 does not have much in common with the one in  3.3.9_001856, either.)

Thanks&Regards
Peter

**Comment by jonathan-reisdorf** [comment]
Hi Peter, have you tried this fork already?
https://github.com/robosophus/rrlogd-patcher
Seems to work for me for version 1898

**Comment by JohnRev** [comment]
Thanks,
I have merged the fork changes here.
